public class AllTheDealers {

    // A class for organizing all the dealer information. Methods for retrieving specific data is at the bottom //

    public String[][] allTheDealers = new String[][]{
            new String[]{"IIROCOOOOOOOOOOOACKF","Acker Finley Inc.", "ACKF", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOACUM","Acumen Capital Finance Partners Limited", "ACUM", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOAGFS","AGF Securities (Canada) Limited", "AGFS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOALCP","Aligned Capital Partners Inc.", "ALCP", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOALLG","All Group Financial Services Inc.", "ALLG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300K6BTPH3TXTDU71","AltaCorp Capital Inc.", "ALTA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOALTU","Altus Securities Inc.", "ALTU", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300W78MBP42KZSP20","Amex Bank of Canada", "AMXB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOARGO","Argosy Securities Inc.", "ARGO", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOARTN","Arton Investments", "ARTN", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOASCM","Assante Capital Management Ltd.", "ASCM", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOASTH","Aston Hill Securities Inc.", "ASTH", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOATBS","ATB Securities Inc.", "ATBS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOAURA","AURAY Capital Canada inc.", "AURA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOB2BB","B2B Bank", "B2BB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOB2BS","B2B Bank Securities Services Inc.", "B2BS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300OLZFLPH7LVXW89","Bank of China (Canada)", "BOCC", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"NQQ6HPCNCCU6TUTQYE16","Bank of Montreal", "BMOB", "Schedule I Bank", "Active", "GSD"},
            new String[]{"549300DG7CU0C6T7Q866","Bank of Tokyo - Mitsubishi UFJ (Canada)", "BOTC", "Schedule II Bank", "Inactive", "Non-GSD"},
            new String[]{"2138009N9TYRBWXPPS04","Barclays Capital Canada Inc.", "BARC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBBSS","BBS Securities Inc.", "BBSS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300OXKJZP9X58ZW12","Beacon Securities Limited", "BEAC", "Dealer Member", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOBLBU","Bloom Burton & Co. Limited", "BLBU", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBBTB","Bloomberg Tradebook Canada Company", "BBTB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300B2SAXGWM7G5218","BMO InvestorLine Inc.", "BMOI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"M3LKFDNSJGJ7TMLH6Z15","BMO Nesbitt Burns Inc.", "BNBI", "Dealer Member", "Active", "GSD"},
            new String[]{"549300UEKTXMTFUVUH42","BNP Paribas (Canada)", "BNPC", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"549300SXQO4RWLD24V90","BNP Paribas (Canada) Valeurs mobilieres inc.", "BNPV", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300Z1YVV8SP8ZNG74","BofA Canada Bank", "BOAB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBRNT","Brant Securities Limited", "BRNT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300BSFCEB31FMD625","Bridgewater Bank", "BRGB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBTAM","BrokerTec Americas LLC", "BTAM", "IDBB", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBRKF","Brookfield Financial Securities LP", "BRKF", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBURG","Burgeonvest Bick Securities Limited", "BURG", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"549300ORF2FMHXODHJ66","Caldwell Securities Ltd.", "CALD", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300T0EM8DDTDWZP60","Canaccord Genuity Corp.", "CGGI", "Dealer Member", "Active", "GSD"},
            new String[]{"2IGI19DL77OX0HC3ZE78","Canadian Imperial Bank of Commerce", "CIBB", "Schedule I Bank", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOCANS","Canadian ShareOwner Investments Inc.", "CANS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300OAHEWZ9NUJL153","Canadian Tire Bank", "CTRB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"549300QG7XFGLKN6HL17","Canadian Western Bank", "CDWB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"5493008EYOZ1SZ0ZN858","CanDeal.ca Inc.", "CAND", "Dealer Member/ATS", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCTRF","Cantor Fitzgerald Canada Corporation", "CTRF", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493003LBDEDV2IVJW19","Casgrain & Company Limited", "CASG", "Dealer Member", "Active", "GSD"},
            new String[]{"54930010155MJH8W7705","CFF Bank", "CFFB", "Schedule I Bank", "Inactive", "Non-GSD"},
            new String[]{"549300FK31BZ6RQI9X62","Chippingham Financial Group Limited", "CHIP", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCHIX","Chi-X Canada ATS Limited", "CHIX", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300C4CDBLRRW04K78","CIBC Investor Services Inc.", "CIBI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300TDJKVQJ41VN031","CIBC World Markets Inc.", "CIBC", "Dealer Member", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOCITG","CIT Group Securities (Canada) Inc.", "CITG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCESC","Citadel Securities Canada ULC", "CESC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300U6C5DCBKSIEB26","Citco Bank Canada", "CTBC", "Schedule II Bank", "Inactive", "Non-GSD"},
            new String[]{"YJW4XPRSVL5L1ANG2086","Citibank Canada", "CBKC", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCITI","Citigroup Global Markets Canada Inc.", "CITI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493009LT0J21LWHNM96","Citizens Bank of Canada", "CBOC", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCLAR","Clarus Securities Inc.", "CLAR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCMCM","CMC Markets Canada Inc.", "CMCM", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300SUH8XF18ZB7M51","Cormark Securities Inc.", "CORM", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300113KPP1G6XWI39","Credential Securities Inc.", "CRED", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300XLNS8GBET6ZF43","Credit Suisse Securities (Canada), Inc.", "CRSU", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300M4EHQ254ACQM10","CS Alterna Bank", "CSAB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCTCB","CTC Bank of Canada", "CTCB", "Schedule II Bank", "Inactive", "Non-GSD"},
            new String[]{"549300NGVLEWZ4CHWB37","CTI Capital Securities Inc.", "CCSI", "Dealer Member", "Active", "GSD"},
            new String[]{"549300UMEEYBCHKH2V58","Cumberland Private Wealth Management Inc.", "CUMB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300ZG5E3QCXPEEF56","Desjardins Securities Inc.", "DESJ", "Dealer Member", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOODRCB","DirectCash Bank", "DRCB", "Schedule I Bank", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOODDSI","Dominick Inc.", "DDSI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300A7UQR6LPFJ3743","Dubeau Capital & Cie Ltee", "DUBE", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300EJ0ZH2Z06TF814","Dundee Securities Ltd.", "DUND", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300E76GGWCYWF5G54","Echelon Wealth Partners Inc.", "EURO", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOEDWJ","Edward Jones", "EDWJ", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOETCC","Electronic Transaction Clearing Canada, Inc.", "ETCC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOEMER","Emerging Equities Inc.", "EMER", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOEQUI","EquiLend Canada Corp.", "EQUI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493004QI4QQE17ETY06","Equitable Bank", "EQBB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"549300514J3G7XH64311","Fidelity Clearing Canada ULC", "FDTY", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOFINA","Financiere des professionnels - Gestion privee inc.", "FINA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOFINX","FIN-XO Securities Inc.", "FINX", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300CXEHGNN6MSF262","First Nations Bank of Canada", "FNBC", "Schedule I Bank", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOFRST","FirstEnergy Capital Corp.", "FRST", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOFOST","Foster & Associates Financial Services Inc.", "FOST", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300UUTCUXYW859441","Freedom International Brokerage Co.", "FREE", "IDBB", "Active", "Non-GSD"},
            new String[]{"SDNHYL6IA3KV4B9UYI13","Friedberg Mercantile Group Ltd.", "FRBG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300QOJUXOGKWJYE25","GAIN Capital - FOREX.com Canada Ltd.", "GAIN", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOBEAN","Gary Bean Securities Ltd.", "BEAN", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOGBOC","General Bank of Canada", "GBOC", "Schedule I Bank", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOGLMX","Global Maxfin Capital Inc.", "GLMX", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOGLOB","Global Securities Corporation", "GLOB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493005JKLVWNZ3BD305","GMP Securities L.P.", "GMPS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493009SS6U10C4KDV21","Goldman Sachs Canada Inc.", "GLDS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOGOOD","Goodwood Inc.", "GOOD", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPORT","Gravitas Securities Inc.", "PORT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300G6DE5CLEBNZG48","Habib Canadian Bank", "HABB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOHAMP","Hampton Securities Limited", "HAMP", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOHARB","Harbourfront Wealth Management Inc.", "HARB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300UUZ6SLQGGQTD76","Haywood Securities Inc.", "HAYW", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOHLCB","Hollis Canadian Bank", "HLCB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOHOME","Home Bank", "HOME", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"549300SP6Z9JX88GD037","HomEquity Bank", "HMEB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"DMB80L5QKUQ124HSYW98","HSBC Bank Canada", "HSBB", "Schedule II Bank", "Active", "GSD"},
            new String[]{"213800NVXC2F29LQVZ83","HSBC Securities (Canada) Inc.", "HSBC", "Dealer Member", "Active", "GSD"},
            new String[]{"549300G8NIYYSMVM6211","ICAP Securities USA LLC", "ICAP", "IDBB", "Active", "Non-GSD"},
            new String[]{"5493000G6B54FO0VAI98","ICICI Bank Canada", "ICIB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOITGI","Independent Trading Group (ITG) Inc.", "ITGI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493005TQRM4H168ZM83","Industrial Alliance Securities Inc.", "INDA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493001CN6FN6RIWPB75","Industrial and Commercial Bank of China (Canada)", "ICBC", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOINFO","Infor Financial Inc.", "INFO", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOICXL","Instinet Canada Cross Limited", "ICXL", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOINCL","Instinet Canada Limited", "INCL", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOINTG","Integral Wealth Securities Limited", "INTG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300QOMHWIXQCEYW57","Interactive Brokers Canada Inc.", "INTR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOINVE","Investors Group Securities Inc.", "INVE", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOIPCS","IPC Securities Corporation", "IPCS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5HPLP7FVD3SPX7MNDL06","ITG Canada Corp.", "ITGC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300Z2NZSU374I1317","J.P. Morgan Bank Canada", "JPMB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"549300F310BOLPDDZ813","J.P. Morgan Securities Canada Inc.", "JPMO", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOJCOB","Jacob Securities Inc.", "JCOB", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOJAMB","Jameson Bank", "JAMB", "Schedule I Bank", "Inactive", "Non-GSD"},
            new String[]{"5493004ZMPUQLD5G1M03","JC Clark Ltd.", "JCCL", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOJEFF","Jefferies Securities, Inc.", "JEFF", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOJCCL","JitneyTrade Inc.", "JITT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOJGCL","Jones, Gable & Company Limited", "JGCL", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOJTCI","JonesTrading Canada Inc.", "JTCI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300ICX01576CECU53","K.J. Harrison & Partners Inc.", "KJHP", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300377KFK0S3U9569","KEB Hana Bank Canada", "KORB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOKERN","Kernaghan & Partners Ltd.", "KERN", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOKCMI","Kingsdale Capital Markets Inc.", "KCMI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300QUTDF2IGYFLO42","Kingwest & Company", "KNGW", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOLKSI","Lakeshore Securities Inc.", "LKSI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"HO0K6ZULL3QE6S6SFW60","Laurentian Bank of Canada", "LBOC", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOLEED","Leede Financial Markets Inc.", "LEED", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOLDJG","Leede Jones Gable Inc.", "LDJG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOLTYR","Lightyear Capital Inc.", "LTYR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOLQNT","Liquidnet Canada Inc.", "LQNT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300XDMU8ZOR16SO31","Lombard Odier Valeurs mobilieres (Canada) inc.", "LOMB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMPTI","M Partners Inc.", "MPTI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300W8DAKQMWLIE556","MacDougall MacDougall & MacTier Inc.", "MACD", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300RUVYKFR2CPFQ75","Mackie Research Capital Corporation", "MACK", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMACQ","Macquarie Capital Markets Canada Ltd.", "MACQ", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMAIS","Maison Placements Canada Inc.", "MAIS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMAND","Mandeville Private Client Inc.", "MAND", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493001ECI4NJPXI5P10","Manulife Bank of Canada", "MBOC", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMANU","Manulife Securities Incorporated", "MANU", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMPLF","Maple Futures Corp.", "MPLF", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"549300SY7KEVRLDRS457","Maple Securities Canada Limited", "MPLS", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMXCC","MarketAxess Canada Company", "MXCC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMAWR","Mawer Direct Investing Ltd.", "MAWR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMPWM","McLean & Partners Wealth Management Ltd.", "MPWM", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMDML","MD Management Limited", "MDML", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300GD2Y6NFWFLC565","Mega International Commercial Bank (Canada)", "MEGB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"QBB7LJ15BSZOYGYACQ50","Merrill Lynch Canada Inc.", "MLCI", "Dealer Member", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOMDLC","Middlefield Capital Corporation", "MDLC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493001B191NKBHPGZ15","Mirabaud Canada Inc.", "MIRA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"54930065FO7CXEUTGL76","Morgan Stanley Canada Limited", "MORG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOMUFG","MUFG Securities (Canada), Ltd.", "MUFG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOONBDB","National Bank Direct Brokerage Inc.", "NBDB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300D83GR71RNG0O65","National Bank Financial Inc.", "NBFI", "Dealer Member", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOONBFL","National Bank Financial Ltd.", "NBFL", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"BSGEFEIOM18Y80CKCV46","National Bank of Canada", "NBOC", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"549300R6OJCZ1R8P6U58","NBCN inc.", "NBCN", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493008VDH0LPUR5EK64","OANDA (Canada) Corporation ULC", "ONDA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOOCSI","Ocean Securities Inc.", "OCSI", "Dealer Member", "Inactive", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOOCCC","Octagon Capital Corporation", "OCCC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300XXGQ3ZBUATAA14","Odlum Brown Limited", "ODLM", "Dealer Member", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOOMGA","Omega Securities Inc.", "OMGA", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOOMGW","OMG Wealth Management Inc.", "OMGW", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300VFT3CN1YF4S615","OTT Financial Canada Inc.", "OTTF", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPACE","PACE Securities Corp.", "PACE", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPRDM","Paradigm Capital Inc.", "PRDM", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"89RLTMP2WM4KXYJMWI06","Pavilion Global Markets Ltd.", "PVLN", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPEAK","PEAK Securities Inc.", "PEAK", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493002DMKJE7H5VGZ78","Perimeter Markets Inc.", "CBID", "Dealer Member/ATS", "Active", "Non-GSD"},
            new String[]{"549300TZNHWOYB544349","Perron & Partners Wealth Management Corp.", "PERR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPERY","Perry Securities Ltd.", "PERY", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493000WV47FDC28QG89","Pershing Securities Canada Limited", "PRSH", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPTRS","Peters & Co. Limited", "PTRS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300IVDRYC7JY3QC31","PI Financial Corp.", "PIFC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300ZW5W660U16FP37","Pictet Canada L.P.", "PICT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"54930047VT047QI4EM75","Polar Asset Management Partners Inc.", "POLR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPOLL","Pollitt & Co. Inc.", "POLL", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPOPE","Pope & Company Limited", "POPE", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"549300Z8EUUJQJFFTO04","President's Choice Bank", "PRCB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOPWLC","PWL Capital Inc.", "PWLC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOQTRD","Qtrade Securities Inc.", "QTRD", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOQUNS","Queensbury Securities Inc.", "QUNS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493006DK8U1EWMPOA81","Questrade, Inc.", "QUES", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300BVOTJ732IIV308","R.J. O'Brien & Associates Canada Inc.", "RJOB", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300Q3FSJ44RJLP108","Raymond James Ltd.", "RAYJ", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300U4H4BEJHJ27M83","RBC Direct Investing Inc.", "RBCD", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300QJJX6CVVUXLE15","RBC Dominion Securities Inc.", "RBCS", "Dealer Member", "Active", "GSD"},
            new String[]{"213800JZRT4GBKN1SR53","RBS Capital Markets (Canada) Limited", "RBSC", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOORNCI","Renaissance Capital Inc.", "RNCI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOORTRF","Retire First Ltd.", "RTRF", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOORGMP","Richardson GMP Limited", "RGMP", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOROGB","Rogers Bank", "ROGB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOORGRS","Rogers Group Investment Advisors Ltd.", "RGRS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOORBRG","Rothenberg Capital Management Inc.", "RBRG", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"ES7IP3U3RHIGC71XBU11","Royal Bank of Canada", "RBOC", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSLMN","Salman Partners Inc.", "SLMN", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSAND","Sandstone Asset Management Inc.", "SAND", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSBER","Sanford C. Bernstein (Canada) Limited", "SBER", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493001XCEF2PSOAOK24","SBI Canada Bank", "INDB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSCMS","SCM Securities LP", "SCMS", "Dealer Member", "Inactive", "Non-GSD"},
            new String[]{"5493009NLZXZGJDOPC94","Scotia Capital Inc.", "SCAP", "Dealer Member", "Active", "GSD"},
            new String[]{"549300UNAODCMZCL4563","Secutor Capital Management Corporation", "SECU", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOCAPS","Sherbrooke Street Capital (SSC) Inc.", "CAPS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300HXFQKKZG38VQ37","Shinhan Bank Canada", "SHNB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"5493009OFT0EK4NI3K23","Shorcan Brokers Ltd.", "SHOR", "IDBB", "Active", "Non-GSD"},
            new String[]{"549300862XUZQ4XPOS53","Societe Generale (Canada)", "SOCG", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"85M6SLXL8PVZZO6V3174","Societe Generale Capital Canada Inc.", "SGCC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSOLI","Solium Financial Inc.", "SOLI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSPRT","Sprott Private Wealth LP", "SPRT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"BJ4CSKBQCK61XM6ZL688","State Street Global Markets Canada Inc.", "STST", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSASI","StephenAvenue Securities Inc.", "SASI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOSTUI","Stuart Investment Management Limited", "STUI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300F6SV5QPUEKHB80","Sumitomo Mitsui Banking Corp. of Canada (Japan)", "SMBC", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"549300OWIL82AHIVP639","Tangerine", "TANG", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"5493006RJSLS5DA4PD75","TD Securities Inc.", "TDSI", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300EM9IELBMKYHT27","TD Waterhouse Canada Inc.", "TDWC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"L3I9ZG2KFGXZ61BMYR72","The Bank of Nova Scotia", "BNSB", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"PT3QB789TSUIDF371261","The Toronto Dominion Bank", "TTDB", "Schedule I Bank", "Active", "GSD"},
            new String[]{"IIROCOOOOOOOOOOOTMBR","Timber Hill Canada Company", "TMBR", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOTRPZ","Trapeze Capital Corp.", "TRPZ", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOTCML","TriAct Canada Marketplace LP", "TCML", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300LXVFYIVZLFL678","Tullett Prebon Canada Ltd.", "TPCL", "IDBB", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOTUSC","Tuscarora Capital Inc.", "TUSC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300A0NSXDTEQJAR30","UBS Bank (Canada)", "UBSB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOUBSS","UBS Securities Canada Inc.", "UBSS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493001JLHK7WY7QPD28","Valeurs Mobilieres Banque Laurentienne Inc.", "VMBL", "Dealer Member", "Active", "GSD"},
            new String[]{"549300K2507QF5P5DT31","Velocity Trade Capital Ltd.", "VLCT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300RUBSDFVNCR7415","VersaBank", "VRSA", "Schedule I Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOWDLC","W.D. Latimer Co. Limited", "WDLC", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOWALB","Walmart Canada Bank", "WALB", "Schedule II Bank", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOWATT","Watt Carmichael Inc.", "WATT", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOWFGO","Wells Fargo Securities Canada, Ltd.", "WFGO", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"5493006M6XIIT33FFZ26","Wolverton Securities Ltd.", "WOLV", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOWLDS","Worldsource Securities Inc.", "WLDS", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"IIROCOOOOOOOOOOOYCFO","yourCFO Advisory Group Inc.", "YCFO", "Dealer Member", "Active", "Non-GSD"},
            new String[]{"549300GRF3S0VG3S4418","Zag Bank", "ZAGB", "Schedule I Bank", "Active", "Non-GSD"}};

    String[] getAllDealerNames(String fieldName){
        String[] names = new String[allTheDealers.length];
        names[0] = fieldName;
        for(int i = 1; i < allTheDealers.length; i++){
            names[i] = allTheDealers[i][1];
        }
        return names;
    }

    String getADealerCode(String string) {
        if (string.isEmpty()) {
            return "";
        } else {
            for (String[] row : allTheDealers) {
                if (row[1].equals(string)) {
                    return row[0];
                }
            }
            return "";
        }
    }

    String getADealerName(String string) {
        if (string.isEmpty()) {
            return "";
        } else {
            for (String[] row : allTheDealers) {
                if (row[0].equals(string)) {
                    return row[1];
                }
            }
            return "";
        }
    }
    }
